-- ============================================
-- BIOVERSE Phase 2 — Database Schema
-- ============================================
-- Jalankan script ini di Supabase SQL Editor.
-- Pastikan tabel `materi` dari Phase 1 sudah ada.
-- ============================================


-- ────────────────────────────────────────────
-- 1. session_state
--    Live state per sesi aktif siswa.
--    Digunakan oleh: Jarvis FSM, Hook, Premack Reward Gate
-- ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.session_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id INT NOT NULL,
    session_id VARCHAR(255) NOT NULL UNIQUE,
    fsm_state VARCHAR(50) NOT NULL DEFAULT 'IDLE_LISTENING',
    current_topic_id INT,
    last_query TEXT,
    last_topic_attempted VARCHAR(255),
    engagement_score FLOAT NOT NULL DEFAULT 100.0,
    current_task_status VARCHAR(50) NOT NULL DEFAULT 'in_progress',
    reward_expires_at TIMESTAMPTZ,
    interaction_budget_seconds INT NOT NULL DEFAULT 60,
    hook_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    hook_idle_threshold_seconds INT NOT NULL DEFAULT 180,
    last_interaction_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_session_state_student_id
    ON public.session_state(student_id);

CREATE INDEX IF NOT EXISTS idx_session_state_session_id
    ON public.session_state(session_id);


-- ────────────────────────────────────────────
-- 2. topic_dependency_graph
--    Prerequisite map antar materi.
--    Digunakan oleh: Jarvis guardrail (bridging response)
-- ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.topic_dependency_graph (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id INT NOT NULL,
    prerequisite_topic_id INT NOT NULL,
    connecting_fact TEXT NOT NULL,
    CONSTRAINT fk_topic
        FOREIGN KEY (topic_id) REFERENCES public.materi(id) ON DELETE CASCADE,
    CONSTRAINT fk_prerequisite
        FOREIGN KEY (prerequisite_topic_id) REFERENCES public.materi(id) ON DELETE CASCADE,
    CONSTRAINT uq_topic_prerequisite
        UNIQUE (topic_id, prerequisite_topic_id)
);


-- ────────────────────────────────────────────
-- 3. caregiver_student_link
--    Relasi otorisasi caregiver ↔ siswa.
--    Dibuat sekarang untuk kesiapan schema,
--    BELUM dipakai di phase ini.
-- ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.caregiver_student_link (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    caregiver_id INT NOT NULL,
    student_id INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_caregiver_student_link_student
    ON public.caregiver_student_link(student_id);


-- ────────────────────────────────────────────
-- 4. interaction_log
--    Audit trail setiap interaksi siswa.
--    Digunakan oleh: Jarvis, Hook, Visual-Haptic
-- ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.interaction_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id INT NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- event_type values:
--   'voice_query'     — Jarvis VUI query
--   'idle_event'      — Hook idle detection
--   'visual_click'    — Tunarungu interactive element
--   'quiz_complete'   — Quiz selesai dikerjakan
--   'reward_claimed'  — Reward Premack diklaim

CREATE INDEX IF NOT EXISTS idx_interaction_log_student
    ON public.interaction_log(student_id);

CREATE INDEX IF NOT EXISTS idx_interaction_log_session
    ON public.interaction_log(session_id);

CREATE INDEX IF NOT EXISTS idx_interaction_log_event_type
    ON public.interaction_log(event_type);


-- ────────────────────────────────────────────
-- 5. ALTER TABLE materi
--    Tambah kolom metadata untuk Jarvis & Tunarungu
-- ────────────────────────────────────────────

ALTER TABLE public.materi
    ADD COLUMN IF NOT EXISTS connecting_fact TEXT,
    ADD COLUMN IF NOT EXISTS vtt_url VARCHAR(255),
    ADD COLUMN IF NOT EXISTS sync_timestamps JSONB,
    ADD COLUMN IF NOT EXISTS sign_language_video_url VARCHAR(255);
